# Document:
# http://simiki.org/docs/configuration.html

url: https://wiki.itabas.com
title: Wiki
keywords: wiki, commands, notes, memos, reminders, 
description: Everything is fake.
author: itabas016
deploy:
  type: rsync
  user: itabas016
  host: master
  dir: /var/www/simiki
